### ISSUE TITLE
Include assets

### ISSUE THREAD

**Issue by ghost** [smcal/Codecademy_P1#3]
https://github.com/smcal/Codecademy_P1/blob/master/index.html#L13

Consider including your website's assets (in this case images) in your project and provide a relative file path to them in your `img` tags. 

It's always better to provide static assets up front instead of depending on external URLs that could fail or otherwise become unavailable.

**Comment by smcal** [comment]
Yeah missed that one.  If someone changes or deletes it my page is now broken.
